### ISSUE TITLE
Error in executors.py -- megahit 

### ISSUE THREAD

**Issue by bharat1912** [marbl/MetaCompass#10]
Apologies, crashed at the final stages. Proceeded as follows:

**I. $git pull https://github.com/marbl/MetaCompass.git**
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 40 (delta 30), reused 8 (delta 6), pack-reused 0
Unpacking objects: 100% (40/40), done.
From https://github.com/marbl/MetaCompass
 * branch            HEAD       -> FETCH_HEAD
Updating 7380e5e..ac03e97
Fast-forward
 bin/select_references.py                |  9 +++++----
 snakemake/config.json                   |  2 +-
 snakemake/metacompass.iter0.paired.py   |  2 +-
 snakemake/metacompass.iter0.py          |  2 +-
 snakemake/metacompass.iter0.unpaired.py | 21 ++++++++++++++-------
 5 files changed, 22 insertions(+), 14 deletions(-)

**II. ERROR (Partial text from screen)**
Finished job 7.
9 of 14 steps (64%) done
Resources before job selection: {'_cores': 4, '_nodes': 9223372036854775807}
Ready jobs (2):
	pilon_contigs
	assemble_unmapped
Selected jobs (1):
	assemble_unmapped
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775806}

Job 4: ---Assemble unmapped reads .
Reason: Missing output files: CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit/final.contigs.fa; Input files updated by another job: CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.1.fq, CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.2.fq

Full Traceback (most recent call last):
  File "/home/bharat/opt/anaconda3/envs/metacompass/lib/python3.6/site-packages/snakemake/executors.py", line 923, in run_wrapper
    log, version, rule, conda_env, None)
  File "/home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/snakemake/metacompass.iter0.paired.py", line 598, in __rule_assemble_unmapped
  File "/home/bharat/opt/anaconda3/envs/metacompass/lib/python3.6/site-packages/snakemake/shell.py", line 88, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'if [[ -s CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.1.fq || -s CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.2.fq ]]; then rm -rf CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit; megahit -o CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit --min-count 3 --min-contig-len 300 --presets meta-sensitive -t 4 -1 CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.1.fq -2 CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.2.fq  1>> CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.megahit.log 2>&1; else touch CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit/final.contigs.fa CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.megahit.log; echo 'No unmapped reads to run de novo assembly' >CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.megahit.log ;fi' returned non-zero exit status 250.

Error in job assemble_unmapped while creating output file CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit/final.contigs.fa.
Full Traceback (most recent call last):
  File "/home/bharat/opt/anaconda3/envs/metacompass/lib/python3.6/site-packages/snakemake/executors.py", line 923, in run_wrapper
    log, version, rule, conda_env, None)
  File "/home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/snakemake/metacompass.iter0.paired.py", line 598, in __rule_assemble_unmapped
  File "/home/bharat/opt/anaconda3/envs/metacompass/lib/python3.6/site-packages/snakemake/shell.py", line 88, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'if [[ -s CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.1.fq || -s CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.2.fq ]]; then rm -rf CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit; megahit -o CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit --min-count 3 --min-contig-len 300 --presets meta-sensitive -t 4 -1 CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.1.fq -2 CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.2.fq  1>> CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.megahit.log 2>&1; else touch CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit/final.contigs.fa CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.megahit.log; echo 'No unmapped reads to run de novo assembly' >CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.megahit.log ;fi' returned non-zero exit status 250.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bharat/opt/anaconda3/envs/metacompass/lib/python3.6/site-packages/snakemake/executors.py", line 326, in _callback
    raise ex
  File "/home/bharat/opt/anaconda3/envs/metacompass/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bharat/opt/anaconda3/envs/metacompass/lib/python3.6/site-packages/snakemake/executors.py", line 935, in run_wrapper
    show_traceback=True))
snakemake.exceptions.RuleException: CalledProcessError in line 206 of /home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/snakemake/metacompass.iter0.paired.py:
Command 'if [[ -s CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.1.fq || -s CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.2.fq ]]; then rm -rf CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit; megahit -o CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit --min-count 3 --min-contig-len 300 --presets meta-sensitive -t 4 -1 CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.1.fq -2 CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.2.fq  1>> CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.megahit.log 2>&1; else touch CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit/final.contigs.fa CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.megahit.log; echo 'No unmapped reads to run de novo assembly' >CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.megahit.log ;fi' returned non-zero exit status 250.
  File "/home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/snakemake/metacompass.iter0.paired.py", line 206, in __rule_assemble_unmapped

RuleException:
CalledProcessError in line 206 of /home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/snakemake/metacompass.iter0.paired.py:
Command 'if [[ -s CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.1.fq || -s CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.2.fq ]]; then rm -rf CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit; megahit -o CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit --min-count 3 --min-contig-len 300 --presets meta-sensitive -t 4 -1 CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.1.fq -2 CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.2.fq  1>> CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.megahit.log 2>&1; else touch CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit/final.contigs.fa CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.megahit.log; echo 'No unmapped reads to run de novo assembly' >CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.megahit.log ;fi' returned non-zero exit status 250.
  File "/home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/snakemake/metacompass.iter0.paired.py", line 206, in __rule_assemble_unmapped
  File "/home/bharat/opt/anaconda3/envs/metacompass/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Releasing 4 _cores (now 4).
Releasing 1 _nodes (now 9223372036854775807).
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
unlocking
removing lock
removing lock
removed all locks
ERROR: snakemake command failed; exiting..

**III. megathit Log:**
(metacompass) bharat@bharat-T3500:~/opt/anaconda3/envs/metacompass/MetaCompass/CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit$ more log
2019-07-27 11:59:31 - MEGAHIT v1.2.6
2019-07-27 11:59:31 - Using megahit_core without POPCNT and BMI2 support, because the features not detected by CPUID 
2019-07-27 11:59:31 - Convert reads to binary library
2019-07-27 11:59:31 - command /home/bharat/opt/anaconda3/envs/metacompass/bin/megahit_core_no_hw_accel buildlib /home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit/tmp/reads.
lib /home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit/tmp/reads.lib
2019-07-27 12:03:04 - b'INFO  sequence/io/sequence_lib.cpp  :   77 - Lib 0 (/home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.1.fq,/home/bharat/opt/anaconda3/envs/m
etacompass/MetaCompass/CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.mc.sam.unmapped.2.fq): pe, 16018132 reads, 300 max length'
2019-07-27 12:03:04 - b'INFO  utils/utils.h                 :  152 - Real: 212.7322\tuser: 31.6104\tsys: 5.8834\tmaxrss: 235248'
2019-07-27 12:03:04 - k-max reset to: 141 
2019-07-27 12:03:04 - Start assembly. Number of CPU threads 4 
2019-07-27 12:03:04 - k list: 21,29,39,49,59,69,79,89,99,109,119,129,141 
2019-07-27 12:03:04 - Memory used: 11330378956
2019-07-27 12:03:04 - Extracting solid (k+1)-mers and building sdbg for k = 21
2019-07-27 12:03:04 - command /home/bharat/opt/anaconda3/envs/metacompass/bin/megahit_core_no_hw_accel read2sdbg -k 21 -m 1 --host_mem 11330378956 --mem_flag 1 --output_prefix /home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001
_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit/tmp/k21/21 --num_cpu_threads 4 --read_lib_file /home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit/tmp/reads.lib
2019-07-27 12:03:04 - b'INFO  sequence/io/sequence_lib.cpp  :  115 - Before reading, sizeof seq_package: 1328551936'
2019-07-27 12:03:13 - b'INFO  sequence/io/sequence_lib.cpp  :  117 - After reading, sizeof seq_package: 1328551936'
2019-07-27 12:03:13 - b'INFO  sorting/read_to_sdbg_s1.cpp   :  105 - 16018132 reads, 300 max read length, 4801627481 total bases'
2019-07-27 12:03:13 - b'INFO  sorting/read_to_sdbg_s1.cpp   :  109 - 2 words per substring'
2019-07-27 12:03:13 - b'INFO  sorting/read_to_sdbg_s1.cpp   :  124 - Number of files for mercy candidate reads: 2'
2019-07-27 12:03:13 - b'INFO  sorting/base_engine.cpp       :  140 - Preparing data...'
2019-07-27 12:03:13 - b'INFO  sorting/read_to_sdbg_s2.cpp   :  103 - 2 words per substring, words per dummy node ($v): 2'
2019-07-27 12:03:13 - b'INFO  sorting/base_engine.cpp       :  145 - Preparing data... Done. Time elapsed: 0.0039'
2019-07-27 12:03:13 - b'INFO  sorting/base_engine.cpp       :  148 - Preparing partitions and calculating bucket sizes...'
2019-07-27 12:03:34 - b'INFO  sorting/base_engine.cpp       :  130 - Lv1 items: 1199279870, Lv2 items: 3260984'
2019-07-27 12:03:34 - b'INFO  sorting/base_engine.cpp       :  132 - Memory of derived class: 1366064680, Memory for Lv1+Lv2: 4823207352'
2019-07-27 12:03:34 - b'INFO  sorting/base_engine.cpp       :  160 - Preparing partitions and calculating bucket sizes... Done. Time elapsed: 20.2475'
2019-07-27 12:03:34 - b'INFO  sorting/base_engine.cpp       :  164 - Start main loop...'
2019-07-27 12:03:34 - b'INFO  sorting/base_engine.cpp       :  178 - Lv1 scanning from bucket 0 to 1317'
2019-07-27 12:04:00 - b'INFO  sorting/base_engine.cpp       :  185 - Lv1 scanning done. Large diff: 0. Time elapsed: 26.2043'
2019-07-27 12:04:54 - b'INFO  sorting/base_engine.cpp       :  191 - Lv1 fetching & sorting done. Time elapsed: 54.4853'
2019-07-27 12:04:54 - b'INFO  sorting/base_engine.cpp       :  178 - Lv1 scanning from bucket 1317 to 3694'
2019-07-27 12:05:23 - b'INFO  sorting/base_engine.cpp       :  185 - Lv1 scanning done. Large diff: 0. Time elapsed: 28.7587'
2019-07-27 12:06:28 - b'INFO  sorting/base_engine.cpp       :  191 - Lv1 fetching & sorting done. Time elapsed: 64.8290'
2019-07-27 12:06:28 - b'INFO  sorting/base_engine.cpp       :  178 - Lv1 scanning from bucket 3694 to 7217'
2019-07-27 12:06:58 - b'INFO  sorting/base_engine.cpp       :  185 - Lv1 scanning done. Large diff: 0. Time elapsed: 30.5164'
2019-07-27 12:08:07 - b'INFO  sorting/base_engine.cpp       :  191 - Lv1 fetching & sorting done. Time elapsed: 68.4976'
2019-07-27 12:08:07 - b'INFO  sorting/base_engine.cpp       :  178 - Lv1 scanning from bucket 7217 to 12266'
2019-07-27 12:08:38 - b'INFO  sorting/base_engine.cpp       :  185 - Lv1 scanning done. Large diff: 0. Time elapsed: 31.2060'
2019-07-27 12:09:50 - b'INFO  sorting/base_engine.cpp       :  191 - Lv1 fetching & sorting done. Time elapsed: 72.0028'
2019-07-27 12:09:50 - b'INFO  sorting/base_engine.cpp       :  178 - Lv1 scanning from bucket 12266 to 19408'
2019-07-27 12:10:22 - b'INFO  sorting/base_engine.cpp       :  185 - Lv1 scanning done. Large diff: 0. Time elapsed: 32.3821'
2019-07-27 12:11:36 - b'INFO  sorting/base_engine.cpp       :  191 - Lv1 fetching & sorting done. Time elapsed: 73.4038'
2019-07-27 12:11:36 - b'INFO  sorting/base_engine.cpp       :  178 - Lv1 scanning from bucket 19408 to 30035'
2019-07-27 12:12:10 - b'INFO  sorting/base_engine.cpp       :  185 - Lv1 scanning done. Large diff: 0. Time elapsed: 33.6176'
2019-07-27 12:13:28 - b'INFO  sorting/base_engine.cpp       :  191 - Lv1 fetching & sorting done. Time elapsed: 78.7099'
2019-07-27 12:13:28 - b'INFO  sorting/base_engine.cpp       :  178 - Lv1 scanning from bucket 30035 to 47361'
2019-07-27 12:14:06 - b'INFO  sorting/base_engine.cpp       :  185 - Lv1 scanning done. Large diff: 0. Time elapsed: 37.5211'
2019-07-27 12:15:30 - b'INFO  sorting/base_engine.cpp       :  191 - Lv1 fetching & sorting done. Time elapsed: 84.4306'
2019-07-27 12:15:30 - b'INFO  sorting/base_engine.cpp       :  178 - Lv1 scanning from bucket 47361 to 65536'
2019-07-27 12:15:58 - b'INFO  sorting/base_engine.cpp       :  185 - Lv1 scanning done. Large diff: 0. Time elapsed: 28.1617'
2019-07-27 12:16:43 - b'INFO  sorting/base_engine.cpp       :  191 - Lv1 fetching & sorting done. Time elapsed: 44.8233'
2019-07-27 12:16:43 - b'INFO  sorting/base_engine.cpp       :  196 - Main loop done. Time elapsed: 789.5767'
2019-07-27 12:16:43 - b'INFO  sorting/base_engine.cpp       :  199 - Postprocessing...'
2019-07-27 12:16:43 - b'INFO  sorting/read_to_sdbg_s2.cpp   :  618 - Number of $ A C G T A- C- G- T-:'
2019-07-27 12:16:43 - b'INFO  sorting/read_to_sdbg_s2.cpp   :  619 - 9553149 476345632 831616175 823988055 478011054 8668645 18122348 18314576 8375755'
2019-07-27 12:16:43 - b'INFO  sorting/read_to_sdbg_s2.cpp   :  624 - Total number of edges: 2672995389'
2019-07-27 12:16:43 - b'INFO  sorting/read_to_sdbg_s2.cpp   :  625 - Total number of ONEs: 2609960916'
2019-07-27 12:16:43 - b'INFO  sorting/read_to_sdbg_s2.cpp   :  627 - Total number of $v edges: 9553149'
2019-07-27 12:16:43 - b'INFO  sorting/base_engine.cpp       :  202 - Postprocess done. Time elapsed: 0.0878'
2019-07-27 12:16:44 - b'INFO  utils/utils.h                 :  152 - Real: 819.1114\tuser: 3197.4817\tsys: 11.6779\tmaxrss: 6072408'
2019-07-27 12:16:45 - Assemble contigs from SdBG for k = 21
2019-07-27 12:16:45 - command /home/bharat/opt/anaconda3/envs/metacompass/bin/megahit_core_no_hw_accel assemble -s /home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit/tmp/k21
/21 -o /home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit/intermediate_contigs/k21 -t 4 --min_standalone 422 --prune_level 2 --merge_len 20 --merge_similar 0.95 --cleaning_r
ounds 5 --disconnect_ratio 0.1 --low_local_ratio 0.2 --cleaning_rounds 5 --min_depth 2 --bubble_level 2 --max_tip_len -1 --careful_bubble
2019-07-27 12:17:59 - b'INFO  main_assemble.cpp             :  129 - Loading succinct de Bruijn graph: /home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit/tmp/k21/21Done. Tim
e elapsed: 74.428029'
2019-07-27 12:17:59 - b'INFO  main_assemble.cpp             :  133 - Number of Edges: 2672995389; K value: 21'
2019-07-27 12:17:59 - b'INFO  main_assemble.cpp             :  140 - Number of CPU threads: 4'
2019-07-27 12:20:52 - b'INFO  assembly/sdbg_pruning.cpp     :  160 - Removing tips with length less than 2; Accumulated tips removed: 428748; time elapsed: 8.9007'
2019-07-27 12:21:06 - b'INFO  assembly/sdbg_pruning.cpp     :  160 - Removing tips with length less than 4; Accumulated tips removed: 1228136; time elapsed: 13.9837'
2019-07-27 12:21:34 - b'INFO  assembly/sdbg_pruning.cpp     :  160 - Removing tips with length less than 8; Accumulated tips removed: 2655594; time elapsed: 28.2101'
2019-07-27 12:22:30 - b'INFO  assembly/sdbg_pruning.cpp     :  160 - Removing tips with length less than 16; Accumulated tips removed: 5100116; time elapsed: 56.3092'
2019-07-27 12:24:00 - b'INFO  assembly/sdbg_pruning.cpp     :  160 - Removing tips with length less than 32; Accumulated tips removed: 8024050; time elapsed: 89.6935'
2019-07-27 12:25:35 - b'INFO  assembly/sdbg_pruning.cpp     :  169 - Removing tips with length less than 42; Accumulated tips removed: 8927490; time elapsed: 95.0219'
2019-07-27 12:25:35 - b'INFO  main_assemble.cpp             :  158 - Tips removal done! Time elapsed(sec): 455.901'
2019-07-27 13:01:51 - b'INFO  assembly/unitig_graph.cpp     :   84 - Graph size without loops: 64623603, palindrome: 4301'
2019-07-27 13:01:53 - b"terminate called after throwing an instance of 'std::bad_alloc'"
2019-07-27 13:01:53 - b'  what():  std::bad_alloc'
2019-07-27 13:01:56 - Error occurs, please refer to /home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit/log for detail
2019-07-27 13:01:56 - Command: /home/bharat/opt/anaconda3/envs/metacompass/bin/megahit_core_no_hw_accel assemble -s /home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit/tmp/k2
1/21 -o /home/bharat/opt/anaconda3/envs/metacompass/MetaCompass/CS1BS.output_270719/CS1BS_ATBW8_GCCAAT_L001_R1.0.assembly.out/CS1BS_ATBW8_GCCAAT_L001_R1.megahit/intermediate_contigs/k21 -t 4 --min_standalone 422 --prune_level 2 --merge_len 20 --merge_similar 0.95 --cleaning_
rounds 5 --disconnect_ratio 0.1 --low_local_ratio 0.2 --cleaning_rounds 5 --min_depth 2 --bubble_level 2 --max_tip_len -1 --careful_bubble; Exit code -6

**Comment by vcepeda** [comment]
Megahit failed. Check if you are using the required megahit version and also run all the tutorial examples if you haven't done it yet.
