### ISSUE TITLE
Error with kmer-mask if input is gz compressed

### ISSUE THREAD

**Issue by michoug** [marbl/MetaCompass#13]
Hi,
I have an error with the kmer-mask command

here is the error :

```
Full Traceback (most recent call last):
  File "/home/michoug/.conda/envs/my_root/lib/python3.5/site-packages/snakemake/executors.py", line 848, in run_wrapper
    version, rule, conda_env)
  File "/ibex/scratch/michoug/MetaCompass/snakemake/metacompass.iter0.paired.py", line 95, in __rule_kmer_mask
    shell:"echo {params.mfilter};python3 %s/bin/mash_filter.py {input.r1} {input.g1} {output.reffile} {params.mfilter} 1>> {log} 2>&1"%(config["mcdir"])
  File "/home/michoug/.conda/envs/my_root/lib/python3.5/site-packages/snakemake/shell.py", line 80, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'kmer-mask -ms 28 -mdb /ibex/scratch/michoug/MetaCompass/refseq/kmer-mask_db/markers.mdb -1 SRR7287240/SRR7287240_1_val_1.merged.fq -clean 0.0 -match 0.01 -nomasking -t 32 -l 515 -o SRR7287240/SRR7287240_1_val_1.marker 1>> SRR7287240/SRR7287240_1_val_1.0.kmermask.log 2>&1' returned non-zero exit status 1
```

and the log of the software

```
ERROR: -l too small for reads:
       a = '=??¡?>?+&=??Ω???$6?`."???P?'
       b = ''
```

I think it's because the file SRR7287240_1_val_1.merged.fq is in fact compressed

**Comment by michoug** [comment]
Hi, I realized that all examples were given with non-compressed fastq files.
If possible, the option to use them could be added in the software

**Comment by vcepeda** [comment]
The new release coming up soon allows compressed gz files.
