### ISSUE TITLE
Error when running MetaCompass

### ISSUE THREAD

**Issue by bgmfddg** [marbl/MetaCompass#25]
Hi,
I am running the following command:
python3 go_metacompass.py  -r NC_040570.1.fasta -1 ERR2040215_1fp.fq -2 ERR2040215_2fp.fq -t 10

And I get the following error:

[Tue Mar  8 10:02:21 2022] Job 7: ---Build index .
[Tue Mar  8 10:02:30 2022] bowtie2-build -o 3 --threads 10 -q NC_040570.1.fasta metacompass_assembly/assembly/mc.index 1>> metacompass_assembly/assembly/mc.index 2>&1;bowtie2 -a --end-to-end --sensitive --no-unal -p 10 -x metacompass_assembly/assembly/mc.index -q -U ../fp/ERR2040215_1fp.fq,../fp/ERR2040215_2fp.fq -S metacompass_assembly/assembly/mc.sam.all > metacompass_assembly/logs/bowtie2map.log 2>&1; python3 /data/12T/fp/software/MetaCompass/bin/best_strata.py metacompass_assembly/assembly/mc.sam.all metacompass_assembly/assembly/mc.sam; rm metacompass_assembly/assembly/mc.sam.all && touch metacompass_assembly/assembly/.run1.ok
Traceback (most recent call last):
  File "/data/12T/fp/software/MetaCompass/bin/best_strata.py", line 13, in <module>
    while line[0]=="@":
IndexError: string index out of range
[Tue Mar  8 10:05:49 2022] Error in rule bowtie2_map:
[Tue Mar  8 10:05:49 2022]     jobid: 7
[Tue Mar  8 10:05:49 2022]     output: metacompass_assembly/assembly/mc.index, metacompass_assembly/assembly/mc.index, metacompass_assembly/assembly/mc.sam, metacompass_assembly/logs/bowtie2map.log

[Tue Mar  8 10:05:49 2022] RuleException:
[Tue Mar  8 10:05:49 2022] CalledProcessError in line 42 of /data/12T/fp/software/MetaCompass/snakemake/metacompass.ref.paired.py:
[Tue Mar  8 10:05:49 2022] Command ' set -euo pipefail;  bowtie2-build -o 3 --threads 10 -q NC_040570.1.fasta metacompass_assembly/assembly/mc.index 1>> metacompass_assembly/assembly/mc.index 2>&1;bowtie2 -a --end-to-end --sensitive --no-unal -p 10 -x metacompass_assembly/assembly/mc.index -q -U ../fp/ERR2040215_1fp.fq,../fp/ERR2040215_2fp.fq -S metacompass_assembly/assembly/mc.sam.all > metacompass_assembly/logs/bowtie2map.log 2>&1; python3 /data/12T/fp/software/MetaCompass/bin/best_strata.py metacompass_assembly/assembly/mc.sam.all metacompass_assembly/assembly/mc.sam; rm metacompass_assembly/assembly/mc.sam.all && touch metacompass_assembly/assembly/.run1.ok ' returned non-zero exit status 1.
[Tue Mar  8 10:05:49 2022]   File "/data/12T/fp/software/MetaCompass/snakemake/metacompass.ref.paired.py", line 42, in __rule_bowtie2_map
[Tue Mar  8 10:05:49 2022]   File "/home/root640/software/miniconda3/envs/fp/lib/python3.6/concurrent/futures/thread.py", line 56, in run
[Tue Mar  8 10:05:49 2022] Removing output files of failed job bowtie2_map since they might be corrupted:
[Tue Mar  8 10:05:49 2022] metacompass_assembly/assembly/mc.index, metacompass_assembly/assembly/mc.index, metacompass_assembly/assembly/mc.sam, metacompass_assembly/logs/bowtie2map.log
[Tue Mar  8 10:05:49 2022] Will exit after finishing currently running jobs.
[Tue Mar  8 10:05:49 2022] Exiting because a job execution failed. Look above for error message
[Tue Mar  8 10:05:49 2022] Complete log: .snakemake/log/2022-03-08T100221.342749.snakemake.log

Do you have any idea why this is happening?
Thanks

**Comment by vcepeda** [comment]
Did you try the readme examples first? Also, please check if mc.sam and mc.sam.all are empty or have very few lines.
