### ISSUE TITLE
Tutorial example 1 only partial output: config.json and/or metacompass.iter0.ref.py issue?

### ISSUE THREAD

**Issue by alexdthomas** [marbl/MetaCompass#5]
Hello, 

I've been trying to check my installation of MetaCompass before running on my data and have it at least one (possibly two, possibly related) issues.  

First, I installed the dependencies and made sure they are in my path.  Then ran the tutorial one example.  

`python go_metacompass.py -r tutorial/Candidatus_Carsonella_ruddii_HT_Thao2000.fasta -P tutorial/thao2000.1.fq,tutorial/thao2000.2.fq -o example1_output -m 1 -t 4`

and got the following output
```
confirming file containing reference genomes exists..
[OK]
checking for dependencies (Bowtie2, Blast, kmermask, Snakemake, etc)
Bowtie2--->[OK]
/home/talex/.pyenv/versions/miniconda3-latest/bin/blastn
Blast+--->[OK]
/home/talex/apps/MetaCompass/bin/kmer-mask
kmer-mask--->[OK]
/home/talex/.pyenv/versions/miniconda3-latest/bin/snakemake
Snakemake--->[OK]
Traceback (most recent call last):
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/snakemake/io.py", line 697, in _load_configfile
    return yaml.load(f)
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/yaml/parser.py", line 550, in parse_flow_mapping_key
    "expected ',' or '}', but got %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a flow mapping
in "/home/talex/apps/MetaCompass/snakemake/config.json", line 1, column 1
expected ',' or '}', but got '<scalar>'
  in "/home/talex/apps/MetaCompass/snakemake/config.json", line 17, column 14
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/talex/.pyenv/versions/miniconda3-latest/bin/snakemake", line 6, in <module>
    sys.exit(snakemake.main())
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/snakemake/__init__.py", line 1017, in main
    max_jobs_per_second=args.max_jobs_per_second)
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/snakemake/__init__.py", line 270, in snakemake
    overwrite_config.update(load_configfile(configfile))
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/snakemake/io.py", line 708, in load_configfile
    config = _load_configfile(configpath)
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/snakemake/io.py", line 699, in _load_configfile
    raise WorkflowError("Config file is not valid JSON or YAML. "
snakemake.exceptions.WorkflowError: Config file is not valid JSON or YAML. In case of YAML, make sure to not mix whitespace and tab indentation.
ERROR: snakemake command failed; exiting..
touch: cannot touch 'example1_output/thao2000.0.assembly.out/run.fail': No such file or directory
```

I investigated the file `/home/talex/apps/MetaCompass/snakemake/config.json` and noticed what I think is incorrect JSON formatting (no expert, kind of just a guess)

```
{
    "sample" : "",
    "r1" : [""],
    "r2" : [""],
    "ru" : [""],
    "reads" : [""],
    "reference":[""],
    "pickref":"breadth",
    "length":100,
    "prefix":".",
    "memory": 50,
    "nthreads": 64,
    "iter": 1,
    "mincov" : 3,
    "minlen" : 100,
    "mfilter" : 0.00005,
    "cogcov" = 10,
    "mcdir": "."

}
```
I think `"cogcov" = 10,` should be `"cogcov" : 10,`, so I updated it and re-ran the example.  I indeed did get a different error. 

```
confirming file containing reference genomes exists..
[OK]
checking for dependencies (Bowtie2, Blast, kmermask, Snakemake, etc)
Bowtie2--->[OK]
/home/talex/.pyenv/versions/miniconda3-latest/bin/blastn
Blast+--->[OK]
/home/talex/apps/MetaCompass/bin/kmer-mask
kmer-mask--->[OK]
/home/talex/.pyenv/versions/miniconda3-latest/bin/snakemake
Snakemake--->[OK]
Full Traceback (most recent call last):
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/snakemake/__init__.py", line 399, in snakemake
    no_hooks=no_hooks)
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/snakemake/workflow.py", line 308, in execute
    dag.init()
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/snakemake/dag.py", line 115, in init
    job = self.update([job])
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/snakemake/dag.py", line 436, in update
    raise exceptions[0]
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/snakemake/dag.py", line 408, in update
    skip_until_dynamic=skip_until_dynamic)
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/snakemake/dag.py", line 468, in update_
    raise ex
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/snakemake/dag.py", line 462, in update_
    job.dynamic_input)
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/snakemake/dag.py", line 436, in update
    raise exceptions[0]
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/snakemake/dag.py", line 408, in update
  skip_until_dynamic=skip_until_dynamic)
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/snakemake/dag.py", line 468, in update_
    raise ex
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/snakemake/dag.py", line 462, in update_
    job.dynamic_input)
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/snakemake/dag.py", line 436, in update
    raise exceptions[0]
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/snakemake/dag.py", line 408, in update
    skip_until_dynamic=skip_until_dynamic)
  File "/home/talex/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/snakemake/dag.py", line 477, in update_
    raise MissingInputException(job.rule, missing_input)
snakemake.exceptions.MissingInputException: Missing input files for rule pilon_map:


MissingInputException in line 72 of /home/talex/apps/MetaCompass/snakemake/metacompass.iter0.ref.py:
Missing input files for rule pilon_map:

unlocking
removed all locks
ERROR: snakemake command failed; exiting..
touch: cannot touch 'example1_output/thao2000.0.assembly.out/run.fail': No such file or directory
```
looking at `/home/talex/apps/MetaCompass/snakemake/metacompass.iter0.ref.py:` I figured it could have something to do with bowtie2...

I found this issue https://github.com/marbl/MetaCompass/issues/3.  So I decided to uninstall MetaCompass, install bowtie2 2.2.9, and create an alias in my `.bash_profile` to override the system version, then reinstalled MetaCompass.  I got the exact same series of errors (before and after updating the `config.json` file.  

here's some info on my dependency installations 
```
pyenv versions
  system
  2.7.12
  2.7.9
  3.1
  3.5.1
  3.6.1
  miniconda2-latest
* miniconda3-latest (set by /home/talex/.pyenv/version)

blastn -version
blastn: 2.6.0+

snakemake --version
3.7.1

bowtie2 -version
Bowtie 2 version 2.2.9 by Ben Langmead (langmea@cs.jhu.edu, www.cs.jhu.edu/~langmea)

samtools --version
samtools 1.6

megahit -version
megahit: MEGAHIT v1.1.3

java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

plenv versions
  system
* 5.18.0 (set by /home/talex/.plenv/version)
```

I've also tried installing the kmer-mask via the meryl installation from  https://sourceforge.net/p/kmer/code/HEAD/tree/trunk/ and also adding using the path to the MetaCompass installation. Above errors identical.  Any help getting this to work would be appreciated.  

Thanks!

**Comment by vcepeda** [comment]
Hi Alex, 
I recommend you to run the stable releases 1.1
https://github.com/marbl/MetaCompass/releases/tag/1.1
The new release will be available next the week.

**Comment by vcepeda** [comment]
Please check the dependencies. Are you using Bowtie2.2.9 and snakemake 3.7.1?
